# Copyright (c) 2020 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.


title: "ocloud Framwork: Service Configuration"
description: "The ocloud framwork creates a foundation for application deployments in Oracle Cloud Infrastructure"
informationalText: "This framework helps operators to set up a hosting environment for enterprise applications in Oracle Cloud Infrastructure (OCI). A base set of resources is provisioned and configured."
schemaVersion: 1.1.0
version: "20210611"
locale: "en"

variableGroups:
- title: "Tenancy"
  visible: true
  variables:
  - tenancy_ocid
  - class

- title: "Service Resident"
  visible: true
  variables:
  - parent
  - compartment_ocid
  - region
  - current_user_ocid
  - organization
  - solution
  - owner
  - stage
  - repository

- title: "Network Options"
  visible: true
  variables:
  - internet
  - nat
  - ipv6
  - segments

- title: "Domain Settings"
  visible: true
  variables:
  - protect
  - domains

variables:
# Tenancy
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier for your tenancy"
    visible: false
    type: string
    required: true

  class:
    title: "Classification"
    description: "Selecting the Universal Credit Consumption (UCC) Model preselects appropriate resource types"
    type: enum
    default: "FREE_TIER"
    required: true
    enum:
      - FREE_TIER
      - TRIAL
      - PAYG
      - UCC

# Service Configuration
  compartment_ocid:
    title: "Compartment ID"
    description: "The Oracle Cloud Identifier for your compartment"
    visible: false
    type: string
    required: true

  region:
    title: "Home Region"
    description: "The Oracle Cloud Identifier for your home region"
    visible: false
    type: string
    required: true
  
  current_user_ocid:
    title: "User ID"
    description: "The Oracle Cloud Identifier for the current user"
    visible: false
    type: string
    required: true
  
  parent:
    title: "Parent Compartment"
    description: "The Oracle Cloud Identifier for the root compartment. The default should only be changed by experienced users."
    type: oci:identity:compartment:id
    dependsOn:
      compartmentId: tenancy_ocid
      accessLevel: ANY
      lifecycleState: ACTIVE
    default: tenancy_ocid
    required: true

  organization:
    title: "Organization"
    description: "Identifier for the organization, owning the service"
    type: string
    default: "Organization"
    minLength: 1
    maxLength: 25
    pattern: "^[a-zA-Z]+$"
    required: true

  solution:
    title: "Name"
    description: "Identifier for the service, the name should be unique within the tenancy"
    type: string
    default: "Service"
    minLength: 1
    maxLength: 25
    pattern: "^[a-zA-Z]+$"
    required: true

  stage:
    title: "Lifecycle Stage"
    description: "Selecting the lifecycle stage preselects an appropriate collection of operational controls"
    type: enum
    default: "DEV"
    required: true
    enum:
      - DEV
      - UAT
      - PROD

  repository:
    title: "Source Code URL"
    description: "Provide an URL to your IaC repository"
    type: string
    required: false

  owner:
    title: "Owner"
    description: "Provide an eMail address for the technical administrator"
    type: string
    required: true

# Network Options
  segments:
    title: "Network Segments"
    visible: false
    description: "Defining a network topology"
    type: list
    required: true

  internet:
    type: enum
    title: "Internet access"
    #default: "ENABLE"
    required: true
    enum:
      - ENABLE
      - DISABLE

  nat:
    type: enum
    title: "NAT for private subnets"
    #default: "ENABLE"
    required: true
    enum:
      - ENABLE
      - DISABLE

  ipv6:
    type: boolean
    title: "IPv6"
    required: true
    default: false

# Administration Domains
  domains:
    title: "Administrator Domains"
    description: "Enabling a seperation of concerns"
    visible: false
    type: list
    required: true

  protect:
    type: boolean
    title: "Protect administrator domains against destroy?"
    required: false