# Copyright (c) 2020 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Kickstart Application Deployments"
description: "The kickstart framwork creates a foundation for application deployments in Oracle Cloud Infrastructure"
informationalText: "This stack helps operators to set up a hosting environment for enterprise applications in Oracle Cloud Infrastructure (OCI). A base set of resources is provisioned and configured."
schemaVersion: 1.1.0
version: "20210611"
locale: "en"

variableGroups:
- title: "Tenancy"
  visible: true
  variables:
  - tenancy_ocid
  - class

- title: "Region"
  visible: true
  variables:
  - location
  - region

- title: "Service"
  visible: true
  variables:
  - parent
  - compartment_ocid
  - current_user_ocid
  - organization
  - solution
  - owner
  - repository

- title: "Lifecycle"
  visible: true
  variables:
  - stage

- title: "Database"
  visible: true
  variables:
  - create_adb
  - adb_type
  - adb_size

- title: "Application Type"
  visible: true
  variables:
  - host
  - nodes
  - container
  - apex

- title: "Network"
  visible: true
  variables:
  - netsettings
  - internet
  - osn
  - nat
  - ipv6
  - management

- title: "Wallet"
  visible: true
  variables:
  - create_wallet
  - wallet

variables:

  adb_type:
    title: "Database Type"
    visible: create_adb
    required: false
    type: enum
    enum:
      - TRANSACTION_PROCESSING
      - APEX
      - DATA_WAREHOUSE
      - JSON

  adb_size:
    title: "Database Size"
    visible: create_adb
    required: false
    type: enum
    enum:
      - small
      - medium
      - large

  class:
    title: "Define service limits related to the contract type"
    description: "Choose the Universal Credit Consumption (UCC) model to select corresponding resource types"
    type: enum
    default: "FREE_TIER"
    required: true
    enum:
      - FREE_TIER
      - TRIAL
      - PAYG
      - UCC

  compartment_ocid:
    title: "Compartment ID"
    description: "A unique identifier that creates a bspoke administrator domains for your service"
    visible: false
    type: string
    required: true

  container:
    type: boolean
    title: "Cloud Native Service"
    required: false

  create_adb:
    type: boolean
    title: "Create an Autonomous Database"
    required: false

  create_wallet:
    type: boolean
    title: "Create a Wallet"
    required: false
  
  current_user_ocid:
    title: "User ID"
    description: "Retrieved OCID for the current user"
    visible: false
    type: string
    required: true

  host:
    type: boolean
    title: "Enterprise Application"
    required: false

  internet:
    type: enum
    title: "Network Access:"
    required: true
    visible: netsettings
    enum:
      - PUBLIC
      - PRIVATE

  ipv6:
    type: boolean
    title: "IPv6"
    required: true
    visible: netsettings
    default: false

  location:
    title: "Select the data center region for the service deployment"
    description: "Before selecting an availability domain in a region, the target region should be activated for a tenancy"
    visible: true
    type: oci:identity:region:name
    default: region
    required: true

  management:
    type: boolean
    title: "Management"
    visible: false
    required: true

  nat:
    type: boolean
    title: "NAT for Private Subnets"
    required: true
    visible: netsettings
    default: true

  netsettings:
    type: boolean
    title: "Advanced Network Settings"
    required: true
    default: false

  nodes:
    type: boolean
    title: "Web Application"
    required: false

  organization:
    title: "Name of the business unit"
    description: "Identifier for the organization that will use the service"
    type: string
    default: "Organization"
    minLength: 1
    maxLength: 25
    pattern: "^[a-zA-Z]+$"
    required: true

  osn:
    type: enum
    title: "Oracle Cloud Services:"
    required: true
    visible: netsettings
    enum:
      - ALL_SERVICES
      - OBJECT_STORAGE
      - DISABLE

  owner:
    title: "Service Administrator"
    description: "The service administrator will receive notifications when the service topology changes"
    type: string
    required: true
    
  parent:
    title: "Parent Compartment"
    description: "The OCID for the root compartment, the default selection should only be changed by an experienced user"
    type: oci:identity:compartment:id
    visible: false
    dependsOn:
      compartmentId: tenancy_ocid
      accessLevel: ANY
      lifecycleState: ACTIVE
    required: true

  region:
    title: "Default region for the user"
    visible: false
    type: string
    required: true

  repository:
    title: "Source code repository for the provisioning scripts (only used for information pusposes)"
    description: "Provide an URL for the code source"
    type: string
    required: false

  solution:
    title: "Name of the solution"
    description: "Identifier for the service, the name should be unique within the tenancy"
    type: string
    default: "Name"
    minLength: 1
    maxLength: 25
    pattern: "^[a-zA-Z]+$"
    required: true

  stage:
    title: "Select the lifecycle stage for the deployment"
    description: "Selecting the lifecycle stage preselects an appropriate collection of operational controls"
    type: enum
    default: "DEVELOPMENT"
    required: true
    enum:
      - DEVELOPMENT
      - TEST
      - PRODUCTION

  tenancy_ocid:
    title: "Tenancy ID"
    description: "A unique identifier for your cloud tenancy"
    visible: false
    type: string
    required: true

  wallet:
    title: "Vault Type"
    visible: create_wallet
    required: false
    type: enum
    enum:
      - Software
      - HSM